### ISSUE TITLE
Try to avoid --runInBand for tests.

### ISSUE THREAD

**Issue by geoknee** [statechannels/nitro-protocol#18]
Without the flag: tests time out, and I currently do not understand why. To reproduce:

`yarn jest --all`.

With the flag, tests would also run faster (concurrently).

**Comment by geoknee** [comment]
I suspect this may be an issue with only having a single `provider` or node to interact with, rather than a problem with the tests themselves. In the future we could think about ways around this (multiple `ganache` instances?), but we should punt this for now as the tests don't take prohibitively long anyway.

**Comment by geoknee** [comment]
For another possible lead, see _Unresolved Promises_ section here https://jestjs.io/docs/en/troubleshooting

**Comment by geoknee** [comment]
Another possible lead: concurrent tests might lead to collisions in the transaction nonce. Depending on whether these are gracefully handled by `ganache`, this might explain the observed behaviour.

**Comment by geoknee** [comment]
I tried giving every test script a unique signer but that didn't solve the problem https://github.com/statechannels/nitro-protocol/compare/gk-do-not-runinband

**Comment by kerzhner** [comment]
[This branch](https://github.com/statechannels/nitro-protocol/tree/jest-parallel-debug) reduces the problem to:
- 2 test suites that are run in parallel, with one unit test per testsuite.
- One of the testsuites hangs listening for an event.

To reproduce:
1. Checkout the branch.
1. Run ganache and deploy contracts.
2. `npx jest test/optimizedForceMove/forceMove.test.ts test/optimizedForceMove/concludeFromChallenge.test.ts --runInBand`
