### ISSUE TITLE
Avoid timers in unit tests

### ISSUE THREAD

**Issue by kerzhner** [statechannels/nitro-protocol#28]
`setTimout` usage such as https://github.com/statechannels/nitro-protocol/blob/master/test/forceMove/test-helpers.ts#L78 results in Jest runner hanging with the message of  
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by geoknee** [comment]
A couple of thoughts: 
1. We don't really need the timeouts, since jest has a global timeout
2. Removing the timeouts does not seem to prevent the error you mention

**Comment by kerzhner** [comment]
There was another issue at play in the `refute.test.ts`. We are declaring an event listener that is never removed for certain test cases.
