### ISSUE TITLE
Use type `uint32` for turn number variables.

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/nitro-protocol#82]
ethers.js accepts a javascript variable `i` of type `number` as a `uint256` as long as `i < 2147483647`. However, it returns `uint256` variables of type `string` no matter how small it is (I think?)

Since we don't expect channels to exceed 5 billion turns (this is over a century assuming one turn per second) we could simplify the awkward type issues by using type `uint32` for turn numbers.

Using [this technique](https://medium.com/@novablitz/storing-structs-is-costing-you-gas-774da988895e), this would also allow us to store the `turnNumRecord` on-chain, as well as `finalizedAt` (if stored as a `uint40` or `uint48`). We can do this by ignoring some of the bits of the hashed channel storage, which increases the hash collision rate to still-very-acceptable levels. Even storing just 32 bits gives us 5 billion to one odds against collisions.

**Comment by tomclose** [comment]
I'm not sure if 5 billion to one is enough. We're not protecting against accidental collisions here, we need to protect against someone purposefully creating a collision. E.g. if you can create where a finalized channel becomes open again, you've broken the force-move guarantees.

**Comment by andrewgordstewart** [comment]
There's always an `n`-to-one chance of an accidental collision: you are hashing more than 256 bits of information into 256 bits, and then comparing it against 256 bits. The optimized forceMove protocol makes no guarantees of the type you're referring to.

My point is that you can adjust how much room the hashed storage takes up according to your risk tolerance. (Maybe 5 billion to one is too risky, but 2^40 ~ 1 quadrillion to one is surely not too risky)

**Comment by tomclose** [comment]
I think the usual approach to the ethers problems is to use `Bignum` instead of `number`.

**Comment by andrewgordstewart** [comment]
> I think the usual approach to the ethers problems is to use Bignum instead of number.

I agree, but there's no real benefit gained when you will not exceed `2^48` (the size of the largest solidity type that ethers considers safe as a `number)

**Comment by lalexgap** [comment]
> I think the usual approach to the ethers problems is to use `Bignum` instead of `number`.

Using `number`s  make it a lot easier for a wallet to store a `turnNumRecord` in state without worrying about how `BN`s serialize/deserialize.

**Comment by tomclose** [comment]
The 'guarantee' I'm referring to is that it's computationally infeasible to find a hash collision.

**Comment by andrewgordstewart** [comment]
I think it's still computationally infeasible to find a hash collision when the odds are 2^128-to-one against you.

**Comment by tomclose** [comment]
Yes, I think that's probably ok too (?). However, I don't think that's true with 2^32 - which was what was originally proposed ..

**Comment by andrewgordstewart** [comment]
The 2^32 was just an example, not a proposal. In the state-channels-research thread on this, I proposed 2^128, and commented that you can tune this threshold to allow for storage of more information.

**Comment by tomclose** [comment]
It seems like the first question to answer here is whether we're happy limiting the maximum turn number to 2^32 in force-move. This seems fairly reasonable to me, but also that it would be worth getting wider feedback, e.g. in a state-channel-research post.

I'm going to close this issue until we've answered that question. (The aim being that issues should record tasks that are immediately actionable.)

**Comment by andrewgordstewart** [comment]
I don't quite understand what requires feedback. We could also increase the limit on turn numbers to 2^48 and still achieve the same, desired outcome of this issue. I fail to see why wider feedback would be required for that change, for example -- it is practically equivalent to a 2^256 limit, when you consider that one state exchange per _microsecond_ -- which isn't even possible given the finite speed of light, unless the participants are nearer than 300m and have incredibly low latency when signing states -- would still take 9 years to exceed 2^48.
